version: '2'

volumes:
    osbsbox-osbs:
    osbsbox-koji-config:
    osbsbox-registry-auth:
    osbsbox-koji-data:

services:

    shared-data:
        build:
          context: shared-data
        hostname: shared-data
        volumes:
            - osbsbox-osbs:/opt/osbs
            - osbsbox-koji-data:/mnt/koji
            - osbsbox-koji-config:/opt/koji-clients
            - osbsbox-registry-auth:/auth
            - ./ssl:/etc/pki/osbs-box:z

    skopeo-lite:
      build: skopeo-lite
      hostname: skopeo-lite

    koji-db:
        build: koji-db
        hostname: koji-db
        environment:
            - POSTGRES_DB=koji
            - POSTGRES_USER=koji
            - POSTGRES_PASSWORD=mypassword

    koji-hub:
        build:
          context: hub
        hostname: koji-hub
        volumes_from:
            - shared-data
        # Need to export ports on workstation so it
        # can be reached from Openshift's pods
        ports:
            - "8080:80"
            - "8083:8083"

    koji-builder:
        build:
          context: koji-builder
        privileged: true
        hostname: koji-builder
        volumes_from:
            - shared-data
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        tmpfs:
            - /run
            - /tmp

    koji-client:
        build:
          context: client
        hostname: koji-client
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        volumes_from:
            - shared-data

    registry:
      image: registry:2
      ports:
        - 5000:5000
      environment:
        REGISTRY_HTTP_TLS_CERTIFICATE: /etc/pki/osbs-box/certs/domain.crt
        REGISTRY_HTTP_TLS_KEY: /etc/pki/osbs-box/certs/domain.key
        REGISTRY_STORAGE_DELETE_ENABLED: "true"
        # REGISTRY_AUTH: htpasswd
        # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      volumes_from:
        - shared-data
